iio: dac: ad5755: mark OF related data as maybe unused
The driver can be compile tested with !CONFIG_OF making certain data
unused (of_device_id is not used for device matching):

  drivers/iio/dac/ad5755.c:865:34: error: ‘ad5755_of_match’ defined but not used [-Werror=unused-const-variable=]

Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>

---

Changes since v1:
1. None.

Although Jonathan expressed need of changes here, they are a bit too
invasive for me thus I am resending it only for completeness.
I understand therefore that patch might not be accepted.