maple_tree-start-using-maple-copy-node-for-destination-checkpatch-fixes
ERROR: code indent should use tabs where possible
#492: FILE: lib/maple_tree.c:3167:
+^I^I^I^I^I         slot_max, ma_pivots(mn, mt),$

ERROR: code indent should use tabs where possible
#493: FILE: lib/maple_tree.c:3168:
+^I^I^I^I^I         ma_slots(mn, mt));$

total: 2 errors, 0 warnings, 721 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

NOTE: Whitespace errors detected.
      You may wish to use scripts/cleanpatch or scripts/cleanfile

./patches/maple_tree-start-using-maple-copy-node-for-destination.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: "Liam R. Howlett" <Liam.Howlett@oracle.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>