mailbox: pl320-ipc: Drop unused xxx_destination functions
set_destination() and clear_destination() are static functions not used
anywhere in the code:

  pl320-ipc.c:48:20: error: unused function 'set_destination' [-Werror,-Wunused-function]
  pl320-ipc.c:54:20: error: unused function 'clear_destination' [-Werror,-Wunused-function]

Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>