media: rc: gpio-ir-tx: drop of_match_ptr for ID table
The driver can match only via the DT table so the table should be always
used and the of_match_ptr does not have any sense (this also allows ACPI
matching via PRP0001, even though it might not be relevant here).  This
also fixes !CONFIG_OF error:

  drivers/media/rc/gpio-ir-tx.c:24:34: error: ‘gpio_ir_tx_of_match’ defined but not used [-Werror=unused-const-variable=]

Reviewed-by: Sean Young <sean@mess.org>
Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>