platform: cznic: fix function parameter names
A invalid prototype made it into a previous patch, causing an clang warning:

drivers/platform/cznic/turris-signing-key.c:25:55: warning: omitting the parameter name in a function definition is a C23 extension [-Wc23-extensions]

and a slightly different warning with gcc-11 and earlier but not gcc-12 and up:

drivers/platform/cznic/turris-signing-key.c: In function 'turris_signing_key_instantiate':
drivers/platform/cznic/turris-signing-key.c:25:43: error: parameter name omitted

Add the parameters to get a clean build with all compilers.

Fixes: 69df81747542 ("platform: cznic: Add keyctl helpers for Turris platform")
Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202503210450.AoOpbJXC-lkp@intel.com/
Signed-off-by: Arnd Bergmann <arnd@arndb.de>