mux: mmio: Fix missing CONFIG_REGMAP_MMIO
MMIO mux uses now regmap_init_mmio(), so one way or another
CONFIG_REGMAP_MMIO should be enabled, because there are no stubs for
!REGMAP_MMIO case:

  ERROR: modpost: "__regmap_init_mmio_clk" [drivers/mux/mux-mmio.ko] undefined!

Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202505150312.dYbBqUhG-lkp@intel.com/
Fixes: 61de83fd8256 ("mux: mmio: Do not use syscon helper to build regmap")
Acked-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
---

Dependency
==========
Patch exposes Kconfig-circular-dependency, which is being fixed by:
https://git.kernel.org/pub/scm/linux/kernel/git/broonie/regmap.git/commit/?h=for-6.16&id=c5a219395b4e6312102a505bfe73aac8f8bada8c
Therefore this should be merged after above change reaches mainline.

Changes in v2
=============
1. Drop drivers/net/ethernet/arc/Kconfig change.
2. Add Arnd Ack (although do not add Jakub's ack because netdev part
   changed/dropped).
3. Update commit msg because there is no circular dependency anymore.

Cc: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Cc: Samuel Holland <samuel@sholland.org>
Cc: Arnd Bergmann <arnd@arndb.de>