ASoC: codecs: wsa884x: Implement temperature reading and hwmon
Read temperature of the speaker and expose it via hwmon interface, which
will be later used during calibration of speaker protection algorithms.

Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>

---

Changes in v3:
1. Replace Kconfig HWMON dependency in favor of
   IS_REACHABLE(CONFIG_HWMON) which solves Kernel Test Robot warning for
   !HWMON and HWMON=y && WSA884x=m

Changes in v2:
1. Add missing dependency on HWMON for y!=m builds (Kernel Test Robot
   report: undefined reference to
   `devm_hwmon_device_register_with_info').