i2c: xiic: hide OF related data for COMPILE_TEST
The driver can be compile tested with !CONFIG_OF making certain data
unused:

  drivers/i2c/busses/i2c-xiic.c:1202:39: error: ‘xiic_2_00’ defined but not used [-Werror=unused-const-variable=]

Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>